config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    patch 'approve'
    patch 'deny'
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :sex, inclusion: %w(M F m f)
  validates :color, inclusion: %w(blue black white red gray yellow brown), presence: true
  validates :name, presence: true

  belongs_to :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :cat_rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, presence: true, inclusion: %w(PENDING APPROVED DENIED)
  validates :cat_id, presence: true

  after_initialize { self.status ||= "PENDING" }

  validate :overlapping_approved_requests

  belongs_to :cat
  belongs_to :user

  def approve!
    self.status = "APPROVED" if self.status == "PENDING"
    CatRentalRequest.transaction do
      self.save!
      overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED" if self.status == "PENDING"
    self.save!
  end

  def pending?
    return true if self.status == "PENDING"
    false
  end
  private
    def overlapping_requests
      CatRentalRequest.find_by_sql(["
        SELECT
          cat_rental_requests.*
        FROM
          cat_rental_requests
        JOIN
          cats ON cat_id = cats.id
        WHERE
          cats.id = ?
          AND
          NOT( ? > end_date OR ? < start_date)
          AND
          status = 'APPROVED'
        ", self.cat_id, self.start_date, self.end_date])
    end

    def overlapping_approved_requests
      return nil if self.status == "DENIED"
      overlapping_requests.each do |request|
        errors.add(:cat_id, "has a conflict") if request.id != self.id
      end
    end

    def overlapping_pending_requests
      CatRentalRequest.find_by_sql(["
        SELECT
          cat_rental_requests.*
        FROM
          cat_rental_requests
        JOIN
          cats ON cat_id = cats.id
        WHERE
          cats.id = ?
          AND
          NOT( ? > end_date OR ? < start_date)
          AND
          status = 'PENDING'
        ", self.cat_id, self.start_date, self.end_date])
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true

  has_many :cats
  has_many :cat_rental_requests

  after_initialize { self.session_token ||= SecureRandom.urlsafe_base64(16) }
  attr_reader :password

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def owned_cat?(cat)
    # return true if user owns the cat
    current_user.id == cat.user_id
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :check_user, only: [:approve, :deny]
  def new
    @request = CatRentalRequest.new
    @cats = Cat.all
  end

  def index
    @requests = CatRentalRequest.all
    @cats = []
    @requests.each do |request|
      @cats << Cat.find_by_id(request.cat_id)
    end
  end

  def create
    new_request = CatRentalRequest.new(request_params)
    if current_user
      new_request.user_id = current_user.id 
      if new_request.save
        redirect_to cats_url
      else
        render html:"You have an error"
      end
    end
  end

  def approve
    request = CatRentalRequest.find_by_id(params[:cat_rental_request_id])
    request.approve!
    redirect_to cat_url(request.cat_id)
  end

  def deny
    request = CatRentalRequest.find_by_id(params[:cat_rental_request_id])
    request.deny!
    redirect_to cat_url(request.cat_id)
  end

  private
    def request_params
      params.require(:request).permit(:cat_id, :start_date, :end_date)
    end

    def check_user
      if current_user.nil?
        flash[:notice] = "Log in to see this page"
        redirect_to new_session_url
      else
        unless owned_cat?(current_cat)
          flash[:notice] = "You do not own this cat"
          redirect_to cats_url
        end
      end
    end

    def current_cat
      pending_request = CatRentalRequest.find_by_id(params[:cat_rental_request_id])
      Cat.find_by_id(pending_request.cat_id)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :own_cat, only: [:edit, :update]
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by_id(params[:id])
    @rentals = @cat.cat_rental_requests.order(:start_date)
  end

  def create
    new_cat = Cat.new(cat_params)
    if current_user
      new_cat.user_id = current_user.id
      if new_cat.save
        redirect_to :cats
      else
        flash.now[:errors] = new_cat.errors.full_messages
        render :new
      end
    else
      flash[:notice] = "Please log in"
      redirect_to new_session_url
    end
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find_by_id(params[:id])
  end

  def update
    @cat = Cat.find_by_id(params[:id])
    @cat.update(cat_params)
    redirect_to cat_url(@cat)
  end

  private
  def cat_params
    params.require(:cat).permit(:name,
                                :sex,
                                :color,
                                :birth_date,
                                :description)
  end

  def own_cat
    if current_user.nil?
      flash[:notice] = "Please log in"
      redirect_to new_session_url
    else
      cat = Cat.where(user_id: current_user.id)
               .where(id: params[:id])
      if cat.empty?
        flash[:notice] = "You do not own this cat."
        redirect_to cats_url
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_to_index
  skip_before_action :redirect_to_index, only: [:destroy]

  def new

  end

  def create
    user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if user.nil?
      flash[:notice] = "Log in failed"
      redirect_to new_session_url
    else
      login!(user)
      redirect_to cats_url
    end

  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  def redirect_to_index
    if current_user
      redirect_to cats_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_index

  def new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User has been created"
      redirect_to cats_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :password)
    end

    def redirect_to_index
      if current_user
        redirect_to cats_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def csrf_token
    <<-HTML.html_safe
      <input type = "hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}">
    HTML
  end

  def owned_cat?(cat)
    # return true if user owns the cat
    return false if current_user.nil?
    current_user.id == cat.user_id
  end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/index.html.erb
<h1>Schedule of Cat Rentals</h1>

<% @requests.each_with_index do |request, idx| %>
<li>
  <ul><strong>Start Date: </strong>
    <%= request.start_date %>
    <br>
    <strong>End Date: </strong>
    <%= request.end_date %>
    <br>
    <strong>Cat Name: </strong>
    <%= @cats[idx].name %>
  </ul>
</li>
<% end %>

app/views/cat_rental_requests/new.html.erb
<h1>Rent a cat</h1>
<%= render partial: "layouts/flashmessages" %>
<form action="<%= cat_rental_requests_url %>" method="POST">
  <%= csrf_token %>
  <label>Cat to rent</label>
  <select name="request[cat_id]">
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>
  <label>Start date</label>
  <input type="date" name="request[start_date]">
  <br>
  <label>End date</label>
  <input type="date" name="request[end_date]">
  <br>
  <button>Submit</button>
</form>

app/views/cats/_form.html.erb
<%= render partial: "layouts/flashmessages" %>

<% if @cat.persisted? %>
<form action="<%= cat_url(@cat) %>" method='POST'>
  <input type="hidden" name="_method" value="PATCH">
<% else %>
<form action="<%= cats_url %>" method='POST'>
<% end %>
  <%= csrf_token %>
  <label>Name</label>
  <input type="text" name="cat[name]" value="<%= @cat.name %>">
  <br>
  <label>Sex</label>
  <input type="radio" name="cat[sex]" value="M" <%= 'checked="true"' if @cat.sex == "M"%>>
  <label>Male</label>
  <input type="radio" name="cat[sex]" value="F" <%= 'checked="true"' if @cat.sex == "F"%>>
  <label>Female</label>
  <br>
  <label>Color</label>
  <select name="cat[color]">
    <option value="blank">     </option>
    <option value="blue" <%= 'selected' if @cat.color == 'blue' %>>Blue</option>
    <option value="black" <%= 'selected' if @cat.color == 'black' %>>Black</option>
    <option value="white" <%= 'selected' if @cat.color == 'white' %>>White</option>
    <option value="red" <%= 'selected' if @cat.color == 'red' %>>Red</option>
    <option value="gray" <%= 'selected' if @cat.color == 'gray' %>>Gray</option>
    <option value="yellow" <%= 'selected' if @cat.color == 'yellow' %>>Yellow</option>
    <option value="brown" <%= 'selected' if @cat.color == 'brown' %>>Brown</option>
  </select>
  <br>
  <label>Birth Date</label>
  <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>
  <label>Description</label>
  <textarea name="cat[description]"><%= @cat.description %></textarea>
  <br>
  <button>Submit</button>
</form>

app/views/cats/edit.html.erb
<h1>Edit this cat</h1>

<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/index.html.erb
<%= render partial: "layouts/flashmessages" %>

<h1>Here are all of the Cats</h1>

<% @cats.each do |cat| %>
<li>
  <ul><a href = "<%= cat_url(cat.id) %>"><%= cat.name %></a></ul>
</li>
<% end %>

app/views/cats/new.html.erb
<h1>Create a new Cat</h1>

<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<p><strong>Information about this cat.</strong></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sex</th>
      <th>Birth Date</th>
      <th>Color</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @cat.name %></td>
      <td><%= @cat.sex %></td>
      <td><%= @cat.birth_date %></td>
      <td><%= @cat.color %></td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>

<h3>Scheduled Rental Periods</h3>
<% @rentals.each do |rental| %>
  <li>
    <ul><strong> </strong>
      <%= rental.user.user_name %>
      <br>
    <ul><strong>Start Date: </strong>
      <%= rental.start_date %>
      <br>
      <strong>End Date: </strong>
      <%= rental.end_date %>
      <br>
      <strong>Status: <%= rental.status %></strong>
      <% if rental.status == "PENDING" && owned_cat?(@cat) %>
        <%= button_to [rental, :approve], method: :patch do %>
          <strong>Approve</strong>
        <% end %>
        <%= button_to [rental, :deny], method: :patch do %>
          <strong>Deny</strong>
        <% end %>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/layouts/_flashmessages.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninetyninecats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user.nil? %>
<a href="<%= new_session_path %>">Log in</a>
<% else %>
<form action="<%= session_path %>" method="POST">
  <%= csrf_token %>
  <input type="hidden" name="_method" value="delete">
  <button>Log out <%= current_user.user_name %></button>
</form>

<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign up here</h1>

<%= render partial: "layouts/flashmessages" %>

<form action="<%= users_url %>" method="POST">
  <%= csrf_token %>
  <label for="user_name">Create a new user name</label>
  <input type="text" name="user[user_name]">
  <br>
  <label for="password">Create a new password</label>
  <input type="password" name="user[password]">
  <button>Sign up!</button>
</form>